### ISSUE TITLE
Issue_incompleteness in downloading the total number of files for some CIVITAI users

### ISSUE THREAD

**Issue by ElRandom78** [Confuzu/CivitAI-Model-grabber#10]
Hi Confuzu,
first of all, I wanna say thanks, for the introduction of the possibility to specify the cathegory that you want to download. It's very useful.

Only one thing:
I retried also this time to download files from CIVITAI user **nochekaiser881**,
but still the download remain uncompleted.

modality used: All ,  

below the log:

Microsoft Windows [Versione 10.0.19045.4291]
(c) Microsoft Corporation. Tutti i diritti sono riservati.

H:\Nuova cartella\CivitAI-Model-grabber\venv\Scripts>activate

```
(venv) H:\Nuova cartella\CivitAI-Model-grabber\venv\Scripts>python civitAI_Model_downloader.py nochekaiser881
Please enter your Civitai API token: f454545fdfzxxe3db4dsdsd45cvvcv12
Please enter the type of content to download (Lora, Checkpoints, Embeddings, Other, or All): All
Processing username: nochekaiser881, Download type: All
Downloading Files:   0%|                                                                                                                 | 0/257 [00:00<?, ?file/s]Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_7135326_for_chizuru ichinose s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_7135324_for_chizuru ichinose s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_3134276_for_mizuharachizuru-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_7135327_for_chizuru ichinose s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_3134290_for_mizuharachizuru-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_7135323_for_chizuru ichinose s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_3134279_for_mizuharachizuru-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_7135325_for_chizuru ichinose s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_3134274_for_mizuharachizuru-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_7135329_for_chizuru ichinose s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_3134275_for_mizuharachizuru-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_7135328_for_chizuru ichinose s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_3134278_for_mizuharachizuru-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_7135330_for_chizuru ichinose s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_3134281_for_mizuharachizuru-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_7135332_for_chizuru ichinose s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_3134277_for_mizuharachizuru-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_7135333_for_chizuru ichinose s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_3134284_for_mizuharachizuru-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_7135337_for_chizuru ichinose s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_3134285_for_mizuharachizuru-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_7135334_for_chizuru ichinose s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_3134286_for_mizuharachizuru-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_7135335_for_chizuru ichinose s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_3134288_for_mizuharachizuru-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_7135336_for_chizuru ichinose s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_3134287_for_mizuharachizuru-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_7135338_for_chizuru ichinose s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_3134289_for_mizuharachizuru-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_7135339_for_chizuru ichinose s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_2997660_for_chizuruichinosepopochichi-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_7135341_for_chizuru ichinose s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_2997657_for_chizuruichinosepopochichi-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_7135340_for_chizuru ichinose s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_2997658_for_chizuruichinosepopochichi-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_7135342_for_chizuru ichinose s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_2997661_for_chizuruichinosepopochichi-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_7135343_for_chizuru ichinose s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_2997659_for_chizuruichinosepopochichi-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_2997662_for_chizuruichinosepopochichi-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_2997666_for_chizuruichinosepopochichi-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_2997663_for_chizuruichinosepopochichi-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_2997664_for_chizuruichinosepopochichi-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_2997665_for_chizuruichinosepopochichi-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_2997673_for_chizuruichinosepopochichi-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_2997672_for_chizuruichinosepopochichi-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_2997676_for_chizuruichinosepopochichi-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_2997675_for_chizuruichinosepopochichi-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Chizuru Ichinose (一ノ瀬ちづる) / Chizuru Mizuhara (水原千鶴) - Rent-a-Girlfriend (Kanojo, Okarishimasu) (彼女、お借りします)_2997674_for_chizuruichinosepopochichi-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Beatrix Amerhauser (ベアトリクス・アメルハウザー) - Zom 100: Bucket List of the Dead (ゾン100～ゾンビになるまでにしたい100のこと～)_4953778_for_beatrix amerhauser s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Beatrix Amerhauser (ベアトリクス・アメルハウザー) - Zom 100: Bucket List of the Dead (ゾン100～ゾンビになるまでにしたい100のこと～)_4947516_for_beatrix amerhauser s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Beatrix Amerhauser (ベアトリクス・アメルハウザー) - Zom 100: Bucket List of the Dead (ゾン100～ゾンビになるまでにしたい100のこと～)_4947518_for_beatrix amerhauser s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Beatrix Amerhauser (ベアトリクス・アメルハウザー) - Zom 100: Bucket List of the Dead (ゾン100～ゾンビになるまでにしたい100のこと～)_4947517_for_beatrix amerhauser s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Beatrix Amerhauser (ベアトリクス・アメルハウザー) - Zom 100: Bucket List of the Dead (ゾン100～ゾンビになるまでにしたい100のこと～)_4947515_for_beatrix amerhauser s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Beatrix Amerhauser (ベアトリクス・アメルハウザー) - Zom 100: Bucket List of the Dead (ゾン100～ゾンビになるまでにしたい100のこと～)_4947519_for_beatrix amerhauser s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Beatrix Amerhauser (ベアトリクス・アメルハウザー) - Zom 100: Bucket List of the Dead (ゾン100～ゾンビになるまでにしたい100のこと～)_4947522_for_beatrix amerhauser s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Beatrix Amerhauser (ベアトリクス・アメルハウザー) - Zom 100: Bucket List of the Dead (ゾン100～ゾンビになるまでにしたい100のこと～)_4947521_for_beatrix amerhauser s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Beatrix Amerhauser (ベアトリクス・アメルハウザー) - Zom 100: Bucket List of the Dead (ゾン100～ゾンビになるまでにしたい100のこと～)_4947524_for_beatrix amerhauser s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Beatrix Amerhauser (ベアトリクス・アメルハウザー) - Zom 100: Bucket List of the Dead (ゾン100～ゾンビになるまでにしたい100のこと～)_4947523_for_beatrix amerhauser s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Beatrix Amerhauser (ベアトリクス・アメルハウザー) - Zom 100: Bucket List of the Dead (ゾン100～ゾンビになるまでにしたい100のこと～)_4947546_for_beatrix amerhauser s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Beatrix Amerhauser (ベアトリクス・アメルハウザー) - Zom 100: Bucket List of the Dead (ゾン100～ゾンビになるまでにしたい100のこと～)_4947549_for_beatrix amerhauser s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Beatrix Amerhauser (ベアトリクス・アメルハウザー) - Zom 100: Bucket List of the Dead (ゾン100～ゾンビになるまでにしたい100のこと～)_4947547_for_beatrix amerhauser s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Beatrix Amerhauser (ベアトリクス・アメルハウザー) - Zom 100: Bucket List of the Dead (ゾン100～ゾンビになるまでにしたい100のこと～)_4947551_for_beatrix amerhauser s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Beatrix Amerhauser (ベアトリクス・アメルハウザー) - Zom 100: Bucket List of the Dead (ゾン100～ゾンビになるまでにしたい100のこと～)_4947548_for_beatrix amerhauser s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Beatrix Amerhauser (ベアトリクス・アメルハウザー) - Zom 100: Bucket List of the Dead (ゾン100～ゾンビになるまでにしたい100のこと～)_4947555_for_beatrix amerhauser s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Beatrix Amerhauser (ベアトリクス・アメルハウザー) - Zom 100: Bucket List of the Dead (ゾン100～ゾンビになるまでにしたい100のこと～)_4947556_for_beatrix amerhauser s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Beatrix Amerhauser (ベアトリクス・アメルハウザー) - Zom 100: Bucket List of the Dead (ゾン100～ゾンビになるまでにしたい100のこと～)_4947557_for_beatrix amerhauser s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Beatrix Amerhauser (ベアトリクス・アメルハウザー) - Zom 100: Bucket List of the Dead (ゾン100～ゾンビになるまでにしたい100のこと～)_4947554_for_beatrix amerhauser s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Warning: Skipping image 'Beatrix Amerhauser (ベアトリクス・アメルハウザー) - Zom 100: Bucket List of the Dead (ゾン100～ゾンビになるまでにしたい100のこと～)_4947552_for_beatrix amerhauser s1-lora-nochekaiser.safetensors.jpeg' due to path length exceeding the limit.
Traceback (most recent call last):
  File "H:\Nuova cartella\CivitAI-Model-grabber\venv\Scripts\civitAI_Model_downloader.py", line 337, in <module>
    process_username(username, download_type)
  File "H:\Nuova cartella\CivitAI-Model-grabber\venv\Scripts\civitAI_Model_downloader.py", line 311, in process_username
    result = future.result()
  File "C:\Users\Francesco\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\Francesco\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\Francesco\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "H:\Nuova cartella\CivitAI-Model-grabber\venv\Scripts\civitAI_Model_downloader.py", line 169, in download_model_files
    os.makedirs(item_dir, exist_ok=True)
  File "C:\Users\Francesco\AppData\Local\Programs\Python\Python310\lib\os.py", line 227, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] La sintassi del nome del file, della directory o del volume non è corretta: 'model_downloads\\nochekaiser881\\Lora\\C.C. "C2, Immortal Witch, Pizza Girl, Zero\'s Mistress, Grey Witch" - Code Geass: Lelouch of the Rebellion (Code Geass: Hangyaku no Lelouch) (コードギアス 反逆のルルーシュ)'

(venv) H:\Nuova cartella\CivitAI-Model-grabber\venv\Scripts>
```

The number of files that has to be downloaded, in total,  is this:
![image](https://github.com/Confuzu/CivitAI-Model-grabber/assets/151367269/ea673585-a636-4f3c-8e3a-61e4cbd5d05e)

But, the number of files that the Grabber has downloaded is much lower:

![image](https://github.com/Confuzu/CivitAI-Model-grabber/assets/151367269/a90d6334-c83d-4013-9ad6-74b5fbaaa410)

Checkpoint ok, downloaded. 
![image](https://github.com/Confuzu/CivitAI-Model-grabber/assets/151367269/a8d0b239-a02a-4ba9-b95e-9907905b8737)

The real problem are Loras.

![image](https://github.com/Confuzu/CivitAI-Model-grabber/assets/151367269/8d1b38f9-3bd5-4f75-98fe-8acc00b785cb)

only 98 elements (folders) downloaded /  3478 elements.

Same problem of uncompleted downloads for user : **Chenkin**

Below the log:

```
Microsoft Windows [Versione 10.0.19045.4291]
(c) Microsoft Corporation. Tutti i diritti sono riservati.

H:\Nuova cartella\CivitAI-Model-grabber\venv\Scripts>activate

(venv) H:\Nuova cartella\CivitAI-Model-grabber\venv\Scripts>python civitAI_Model_downloader.py Chenkin
Please enter your Civitai API token: f454545fdfzxxe3db4dsdsd45cvvcv12
Please enter the type of content to download (Lora, Checkpoints, Embeddings, Other, or All): Lora
Processing username: Chenkin, Download type: Lora
Traceback (most recent call last):
  File "H:\Nuova cartella\CivitAI-Model-grabber\venv\Scripts\civitAI_Model_downloader.py", line 337, in <module>
    process_username(username, download_type)
  File "H:\Nuova cartella\CivitAI-Model-grabber\venv\Scripts\civitAI_Model_downloader.py", line 311, in process_username
    result = future.result()
  File "C:\Users\Francesco\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\Francesco\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\Francesco\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "H:\Nuova cartella\CivitAI-Model-grabber\venv\Scripts\civitAI_Model_downloader.py", line 169, in download_model_files
    os.makedirs(item_dir, exist_ok=True)
  File "C:\Users\Francesco\AppData\Local\Programs\Python\Python310\lib\os.py", line 227, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] La sintassi del nome del file, della directory o del volume non è corretta: 'model_downloads\\Chenkin\\Lora\\Gridman Universe 古利特宇宙    SDXL_SD1.5 宝多六花 |  新条茜  |  南梦芽'

(venv) H:\Nuova cartella\CivitAI-Model-grabber\venv\Scripts>
```

Total number of files for **Chenkin**:

![image](https://github.com/Confuzu/CivitAI-Model-grabber/assets/151367269/91c26680-d1d7-4cdb-b0cd-a67a34311dfe)

Below the results :

![image](https://github.com/Confuzu/CivitAI-Model-grabber/assets/151367269/7272f92f-2e0e-4785-8212-337937f55146)

only 94 elements (folders) downloaded /  272 elements.

Can you try with these users and see if you have same results as me, please?

**Comment by Worldgate** [comment]
Will run it via linux on the user 'Chenkin' and report once it's done.  I only have 50mbps usually, so might take a while, figure overnight will probably grab what it can and finish.

**Comment by Worldgate** [comment]
Well, when I ran it, it said it was getting 100, so maybe civitai times out at a certain amount?

**Comment by Confuzu** [comment]
I fixed the bug and built in a better char filter. For more info's read 0.3 Bugfix & Changes  on the front page
