### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ElRandom78** [Confuzu/CivitAI-Model-grabber#12]
Hi everyone,

I'm writing to ask if there's any way to fix the error mentioned in the title.

Encountered this error when I tried to download files from user : Chenkin (total of 279 elements)

Below the log:

```
H:\CONFUZU_CivitAI-Model-grabber\venv\Scripts>activate

(venv) H:\CONFUZU_CivitAI-Model-grabber\venv\Scripts>python civitAI_Model_downloader.py Chenkin
Please enter your Civitai API token: fe112369f9901ce567f29e3db4d380d1
Please enter the type of content to download (Lora, Checkpoints, Embeddings, Other, or All): Lora
Processing username: Chenkin, Download type: Lora
Traceback (most recent call last):
  File "H:\...[]_CONFUZU_CivitAI-Model-grabber__THE_VERY_LASTTT_VERSION\venv\Scripts\civitAI_Model_downloader.py", line 355, in <module>                                         | 0.00/75.6M [00:00<?, ?B/s]
    process_username(username, download_type)
  File "H:\...[]_CONFUZU_CivitAI-Model-grabber__THE_VERY_LASTTT_VERSION\venv\Scripts\civitAI_Model_downloader.py", line 329, in process_username
    result = future.result()
  File "C:\Users\Francesco\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Users\Francesco\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\Francesco\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "H:\...[]_CONFUZU_CivitAI-Model-grabber__THE_VERY_LASTTT_VERSION\venv\Scripts\civitAI_Model_downloader.py", line 207, in download_model_files
    download_file_or_image(file_url, file_path)
  File "H:\...[]_CONFUZU_CivitAI-Model-grabber__THE_VERY_LASTTT_VERSION\venv\Scripts\civitAI_Model_downloader.py", line 116, in download_file_or_image
    with open(output_path, "wb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'model_downloads\\Chenkin\\Lora\\浦和ハナコ(水着) _ 碧蓝档案 blue archive  \\swhuazi_v1.safetensors'

(venv) H:\CONFUZU_CivitAI-Model-grabber\venv\Scripts>
```

The problematic file mentioned in the error is at this link:
https://civitai.com/models/115301/or-blue-archive

I noticed one thing: 

The code create the destination folder for the file, but is empty, as shown below:
![image](https://github.com/Confuzu/CivitAI-Model-grabber/assets/151367269/370d7638-2ab9-4d2d-85f9-866247fb8223)

The strangeness, is that the file is available to download in the site, if you try, normally as ever,
but is like the algorythm can't download the file because for him it doen't exist.

so, the download remains interrupted in this point.

**Comment by Confuzu** [comment]
working on a solution
