### ISSUE TITLE
Not downloading every model_error persist_OSError: [WinError 123]

### ISSUE THREAD

**Issue by ElRandom78** [Confuzu/CivitAI-Model-grabber#6]
-

**Comment by ElRandom78** [comment]
I've also made another try, this time with user : '**justTNP**' 
I've encountered same error of before :  "OSError: [WinError 123] The filename, directory name, directory name, or volume label syntax is incorrect"

```
H:\Private\Confuzu_last_Grabber\CivitAI-Model-grabber\venv\Scripts>python civitAI_Model_downloader.py justTNP
Please enter your Civitai API token: 775d795c5e309fe91bc036e49d601156
Traceback (most recent call last):
  File "H:\Private\Confuzu_last_Grabber\CivitAI-Model-grabber\venv\Scripts\civitAI_Model_downloader.py", line 293, in <module>
    process_username(username)
  File "H:\Private\Confuzu_last_Grabber\CivitAI-Model-grabber\venv\Scripts\civitAI_Model_downloader.py", line 271, in process_username
    result = future.result()
  File "C:\Users\Francesco\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\Francesco\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\Francesco\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "H:\Private\Confuzu_last_Grabber\CivitAI-Model-grabber\venv\Scripts\civitAI_Model_downloader.py", line 136, in download_model_files
    os.makedirs(item_dir, exist_ok=True)
  File "C:\Users\Francesco\AppData\Local\Programs\Python\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] La sintassi del nome del file, della directory o del volume non è corretta: 'model_downloads\\justTNP\\[1.5_XL 1.0] Makima | Chainsaw Man'

H:\Private\Confuzu_last_Grabber\CivitAI-Model-grabber\venv\Scripts>
```

so, this break the code and the download iteration stop too soon beacause of the syntax error?
